

name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  install-pip-deps:
    
    runs-on: self-hosted

    
    steps:
      - uses: actions/checkout@v3.5.2
      - name: install pip-dependencies
        run: echo ... install pip dependencies ... 
  deploy-to-dev: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to dev
        run: echo ... Deploying to development environment ... 
  tests-on-dev:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on dev
        run: echo ... Running tests on development environment ... 
  deploy-to-staging: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to staging
        run: echo ... Deploying to staging environment ... 
  tests-on-staging:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on staging
        run: echo ... Running tests on staging environment ... 
  deploy-to-preprod: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to preprod
        run: echo ... Deploying to pre-production environment ... 
  tests-on-preprod:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on preprod
        run: echo ... Running tests on pre-production environment ... 
  deploy-to-prod: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to prod
        run: echo ... Deploying to production environment ... 
  tests-on-prod:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on prod
        run: echo ... Running tests on production environment ... 
