

name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  install-pip-deps:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run install pip-deps
        run: echo ... install-pip-deps success ... 
  deploy-to-dev: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to dev
        run: echo ... deploy-to-dev success ... 
  tests-on-dev:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on dev
        run: echo ... tests-on-dev success ... 
  deploy-to-staging: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to staging
        run: echo ... deploy-to-staging success ... 
  tests-on-staging:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on staging
        run: echo ... tests-on-staging success ... 
  deploy-to-preprod: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to preprod
        run: echo ... deploy-to-preprod success ... 
  tests-on-preprod:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on preprod
        run: echo ... tests-on-preprod success ... 
  deploy-to-prod: 
    runs-on: self-hosted


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to prod
        run: echo ... deploy-to-prod success ... 
  tests-on-prod:
    
    runs-on: self-hosted

    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on prod
        run: echo ... tests-on-prod success ... 
