

name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  
  install-pip-deps:
    name: install pip deps
    runs-on: self-hosted

    
    steps:
      - uses: actions/checkout@v3.5.2
        with: 
          repository: 'spmacc/python-greetings'
          path: python-greetings
      - name: Install pip dependencies
        working-directory: python-greetings
        run: |
          echo "Installing all required dependencies.."
          pip3 install -r requirements.txt
  deploy-to-dev: 
    name: deploy dev 
    runs-on: self-hosted
    needs: install-pip-deps


    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to dev
        run: echo ... Deploying to development environment ... 
  tests-on-dev:
    name: tests on dev
    runs-on: self-hosted
    needs: deploy-to-dev
    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on dev
        run: echo ... Running tests on development environment ... 
  deploy-to-staging: 
    name: deploy to staging
    runs-on: self-hosted
    needs: tests-on-dev 

    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to staging
        run: echo ... Deploying to staging environment ... 
  tests-on-staging:
    name: tests on staging
    runs-on: self-hosted
    needs: deploy-to-staging
    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on staging
        run: echo ... Running tests on staging environment ... 
  deploy-to-preprod: 
    name: deploy to preprod
    runs-on: self-hosted
    needs: tests-on-staging

    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to preprod
        run: echo ... Deploying to pre-production environment ... 
  tests-on-preprod:
    name: tests on preprod
    runs-on: self-hosted
    needs: deploy-to-preprod
    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on preprod
        run: echo ... Running tests on pre-production environment ... 
  deploy-to-prod: 
    name: deploy to prod
    runs-on: self-hosted
    needs: tests-on-preprod

    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run deploy to prod
        run: echo ... Deploying to production environment ... 
  tests-on-prod:
    name: tests on 
    runs-on: self-hosted
    needs: deploy-to-prod
    
    steps:
      
      - uses: actions/checkout@v4

     
      - name: Run tests on prod
        run: echo ... Running tests on production environment ... 
